name: pytest
on: workflow_dispatch

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone respository
        run: |
          git clone https://github.com/tedfuture/workflowsdemo.git
          cd workflowsdemo
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
